set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR arm)

set(TOOLCHAIN_VERSION "8.3.1-1.3")

set(TOOLCHAIN_PREFIX "arm-none-eabi-")
if (WIN32)
    set(TOOLCHAIN_PATH "C:/data/tools/arm/gcc/${TOOLCHAIN_VERSION}/bin/")
    set(TOOLCHAIN_EXT ".exe")
    set(TOOLS_PATH "C:/data/tools/common/medref/")
else ()
    set(TOOLCHAIN_PATH "/opt/gcc-arm-none-eabi-10-2020-q4-major/bin/")
    set(TOOLCHAIN_EXT "")
    set(TOOLS_PATH "")
endif ()

set(CMAKE_C_COMPILER ${TOOLCHAIN_PATH}${TOOLCHAIN_PREFIX}gcc${TOOLCHAIN_EXT})
set(CMAKE_CXX_COMPILER ${TOOLCHAIN_PATH}${TOOLCHAIN_PREFIX}g++${TOOLCHAIN_EXT})
set(CMAKE_LINKER ${TOOLCHAIN_PATH}${TOOLCHAIN_PREFIX}ld${TOOLCHAIN_EXT})
set(CMAKE_ARCHIVER ${TOOLCHAIN_PATH}${TOOLCHAIN_PREFIX}ar${TOOLCHAIN_EXT})

set(CMAKE_OBJCOPY ${TOOLCHAIN_PATH}${TOOLCHAIN_PREFIX}objcopy${TOOLCHAIN_EXT}
    CACHE FILEPATH "" FORCE)

if (WIN32)
    set(CMAKE_CAT type
        CACHE FILEPATH "" FORCE)
else ()
    set(CMAKE_CAT "${TOOLS_PATH}cat${TOOLCHAIN_EXT}"
        CACHE FILEPATH "" FORCE)
endif ()

set(CMAKE_SREC_CAT "${TOOLS_PATH}srec_cat${TOOLCHAIN_EXT}"
    CACHE FILEPATH "" FORCE)

set(CMAKE_CRC32 "${TOOLS_PATH}crc32${TOOLCHAIN_EXT}"
    CACHE FILEPATH "" FORCE)

set(CMAKE_PREPAREFILES "${TOOLS_PATH}Preparefiles${TOOLCHAIN_EXT}"
    CACHE FILEPATH "" FORCE)

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY )
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY )
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY )
